// Vercel Cron备份 — 每天16:00运行。Mac离线时兜底，用腾讯API抓所有能抓的数据
export default async function handler(req, res) {
  const today = new Date().toISOString().split('T')[0]
  const result = { fetched: today, indices: {}, external: {}, pool: [], committed: false }
  const H = { 'User-Agent': 'Mozilla/5.0' }

  async function tx(code) {
    const r = await fetch(`https://qt.gtimg.cn/q=${code}`, { headers: H, signal: AbortSignal.timeout(6000) })
    return r.ok ? r.text() : ''
  }

  // 指数
  const idxMap = [['sh000001','上证'],['sz399001','深成指'],['sz399006','创业板'],['sh000688','科创50']]
  let totalVol = 0
  for (const [code, name] of idxMap) {
    try {
      const t = await tx(code); const parts = t.split('~')
      const price = parseFloat(parts[3]) || 0
      const m = t.match(/(\d{14})~(-?[\d.]+)~(-?[\d.]+)~/)
      const chg = m ? parseFloat(m[3]) : 0
      const amt = parseFloat(parts[37])/1e8 || 0
      result.indices[name] = { close: Math.round(price*100)/100, chg: chg.toFixed(2)+'%', vol: Math.round(amt) }
      if (name === '上证' || name === '深成指') totalVol += amt
    } catch {}
  }

  // 纳指
  try {
    const t = await tx('usIXIC')
    const m = t.match(/(\d{4}-\d{2}-\d{2}[\s\d:]+)~([\d.-]+)~([\d.-]+)~/)
    if (m) result.external.nasdaq = parseFloat(m[3]).toFixed(2) + '%'
  } catch {}

  // 池子
  const poolStocks = [
    ['sh600176','中国巨石'],['sh603986','兆易创新'],['sz000811','冰轮环境'],
    ['sh605111','新洁能'],['sz002384','东山精密'],['sz000636','风华高科'],
    ['sh600183','生益科技'],['sz002281','光迅科技'],
  ]
  for (const [code, name] of poolStocks) {
    try {
      const t = await tx(code); const parts = t.split('~')
      const price = parseFloat(parts[3]) || 0
      const m = t.match(/(\d{14})~(-?[\d.]+)~(-?[\d.]+)~/)
      const chg = m ? parseFloat(m[3]) : 0
      let clr = '🟡'; if (chg > 0) clr = '🟢'; if (chg < -5) clr = '🔴'
      result.pool.push({ status: clr, stock: name, today: chg.toFixed(2)+'%', close: price })
    } catch {}
  }

  // 写入GitHub（只在文件不存在或数据为空时写入）
  const token = process.env.GH_TOKEN
  if (token) {
    try {
      const p = 'data/' + today + '.json'
      const u = 'https://api.github.com/repos/ponylin06/daily-recap/contents/' + p
      const A = { Authorization: 'Bearer ' + token, Accept: 'application/vnd.github+json' }
      const ex = await (await fetch(u, { headers: A })).json()

      let old = {}
      if (ex.content) {
        old = JSON.parse(Buffer.from(ex.content, 'base64').toString())
      }

      // 只在Mac没跑过时才写入（Mac有涨跌停数据）
      const macRan = (old.limitUp || 0) > 0
      if (!macRan) {
        old.date = today
        old.indices = result.indices
        old.external = result.external
        old.poolStatus = result.pool
        old.totalVolume = (totalVol/1e4).toFixed(2) + '万亿'
        old.autoGenerated = true
        old.upCount = 0; old.downCount = 0
        old.limitUp = 0; old.limitDown = 0

        const c = Buffer.from(JSON.stringify(old, null, 2), 'utf-8').toString('base64')
        const body = JSON.stringify({
          message: '🤖 Vercel备份 ' + today,
          content: c,
          sha: ex.sha || '',
          branch: 'main'
        })
        await fetch(u, { method: 'PUT', headers: A, body })
        result.committed = true
      } else {
        // Mac已跑过，只补池子
        if (result.pool.length > 0) old.poolStatus = result.pool
        const c = Buffer.from(JSON.stringify(old, null, 2), 'utf-8').toString('base64')
        await fetch(u, { method: 'PUT', headers: A,
          body: JSON.stringify({ message: '🤖 Vercel补池子 ' + today, content: c, sha: ex.sha, branch: 'main' })
        })
        result.committed = true
      }
    } catch(e) { result.error = e.message }
  }

  // AI分析 (DeepSeek)
  const dsKey = process.env.DEEPSEEK_KEY
  if (dsKey && result.indices['上证']?.close > 0) {
    try {
      const aiPrompt = `A股复盘。上证${result.indices['上证'].close}(${result.indices['上证'].chg}) 深${result.indices['深成指']?.chg} 创${result.indices['创业板']?.chg} 科创${result.indices['科创50']?.chg}。成交${(totalVol/1e4).toFixed(2)}万亿。纳指${result.external.nasdaq}。输出JSON:{"sentimentNote":"情绪一句","cycleNature":"周期一句","visibleLines":"明线排序","hiddenLines":"暗线逻辑","capitalFlow":"资金判断","strategy":"明日策略","risks":["风险1","风险2"]}`
      const aiResp = await fetch('https://api.deepseek.com/v1/chat/completions', {
        method:'POST',
        headers:{'Content-Type':'application/json','Authorization':`Bearer ${dsKey}`},
        body: JSON.stringify({model:'deepseek-chat',messages:[{role:'user',content:aiPrompt}],max_tokens:1000})
      })
      const aiJson = await aiResp.json()
      const aiText = aiJson.choices?.[0]?.message?.content || ''
      const m = aiText.match(/\{[\s\S]*\}/)
      if (m) {
        const ai = JSON.parse(m[0])
        if (!old.sentiment) old.sentiment = {}
        old.sentiment.note = ai.sentimentNote || ''
        if (!old.cycle) old.cycle = {}
        old.cycle.nature = ai.cycleNature || ''
        old.visibleLines = ai.visibleLines || ''
        old.hiddenLines = ai.hiddenLines || ''
        old.capitalFlow = ai.capitalFlow || ''
        old.strategy = ai.strategy || ''
        old.risks = ai.risks || ['']
        result.aiGenerated = true
      }
    } catch(e) { result.aiError = e.message }
  }

  res.status(200).json(result)
}
