#!/usr/bin/env python3
"""每日复盘数据抓取 + AI分析 — GitHub Actions 自动运行"""
import json, os, sys, re
from datetime import datetime, timezone, timedelta
import urllib.request

TZ = timezone(timedelta(hours=8))
NOW = datetime.now(TZ)
TODAY = NOW.strftime('%Y-%m-%d')
WEEKDAYS = ['周一','周二','周三','周四','周五','周六','周日']
WEEKDAY = WEEKDAYS[NOW.weekday()]

if NOW.weekday() >= 5:
    print(f"今日 {WEEKDAY}，非交易日，跳过"); sys.exit(0)

def api(path):
    req = urllib.request.Request(
        f"https://push2.eastmoney.com/api/qt{path}",
        headers={'User-Agent': 'Mozilla/5.0','Referer': 'https://data.eastmoney.com/'})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())

# ===== 1. 指数 =====
idx = api("/ulist.np/get?fltt=2&fields=f2,f3,f6,f170,f171&secids=1.000001,0.399001,0.399006,1.000688,0.899050")
diffs = idx['data']['diff']
names = ['上证','深成指','创业板','科创50','北证50']
indices = {}
for i, n in enumerate(names):
    d = diffs[i]
    indices[n] = {'close': d['f2'], 'chg': f"{d['f3']:+.2f}%", 'vol': round(d.get('f6',0)/1e8) if d.get('f6') else 0}
up_count = diffs[0].get('f170',0)
dn_count = diffs[0].get('f171',0)
total_vol = round(sum(d.get('f6',0) for d in diffs)/1e8)

# ===== 2. 涨跌停 =====
def limit(rise=True):
    try:
        u = '&downt=1' if not rise else ''
        d = api(f"/clt/get?np=1&pn=1&pz=1&fs=m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23&fltt=2{u}")
        return d['data']['total']
    except: return 0
limit_up = limit(True)
limit_down = limit(False)

# ===== 3. 美股 + 池子 =====
ext_data = {"nasdaq":"N/A","note":""}
try:
    us = api("/ulist.np/get?fltt=2&fields=f3&secids=100.NDX,100.DJIA,100.SPCS")
    ext_data["nasdaq"] = f"{us['data']['diff'][0]['f3']:+.2f}%"
except: pass

pool_codes = "1.000636,0.600183,1.600176,0.002384,0.002281,0.000657,1.603986,1.605589,0.002080,1.603256,1.605376,1.600226,1.605111,0.002859,0.000811,1.603186,1.603002,1.600110,0.002741"
pool_data = api(f"/ulist.np/get?fltt=2&fields=f2,f3,f14&secids={pool_codes}")
pool_status = []
for d in pool_data['data']['diff']:
    st = '🟢' if d['f3']>0 else ('🔴' if d['f3']<-5 else ('🟡' if d['f3']<0 else '⚪'))
    pool_status.append({'status':st,'stock':d['f14'],'today':f"{d['f3']:+.2f}%",'ma5':'站上' if d['f3']>-3 else ('跌破' if d['f3']<-7 else '边缘')})

# ===== 4. 组装 JSON =====
recap = {
    "date":TODAY,"weekday":WEEKDAY,"autoGenerated":True,
    "external":ext_data,"indices":indices,
    "totalVolume":f"{total_vol/10000:.2f}万亿" if total_vol>10000 else f"{total_vol}亿",
    "upCount":up_count,"downCount":dn_count,"limitUp":limit_up,"limitDown":limit_down,
    "poolStatus":pool_status,
    "sentiment":{"limitUp":limit_up,"limitDown":limit_down,"upCount":up_count,"downCount":dn_count,"note":"AI分析中"},
    "cycle":{"stage":"","nature":"","pivot":"6.15","days":(NOW-datetime(2026,6,15,tzinfo=TZ)).days},
    "selfQA":"","strategy":"","visibleLines":"","hiddenLines":"","capitalFlow":"","risks":[""],
    "ladder":[],"keyMoments":[],"auction":[],"newsEvents":[],"divergence":[],"seeSaw":[],"volumeProfile":[]
}

# ===== 5. AI 分析 =====
KEY = os.environ.get('DEEPSEEK_KEY','')
if KEY:
    pool_best = [p for p in pool_status if '涨停' in p['today'] or (p['today'].startswith('+') and float(p['today'].replace('%',''))>5)]
    pool_best_str = '，'.join([f"{p['stock']}{p['today']}" for p in pool_best[:5]]) or '无'
    prompt = f"""A股复盘。上证{indices['上证']['close']}({indices['上证']['chg']})深成指{indices['深成指']['chg']}创业板{indices['创业板']['chg']}科创50{indices['科创50']['chg']}。成交{recap['totalVolume']}。涨停{limit_up}跌停{limit_down}。涨{up_count}跌{dn_count}。纳指{ext_data['nasdaq']}。池子最强:{pool_best_str}。输出JSON:{{"sentimentNote":"情绪一句","cycleNature":"周期一句","visibleLines":"明线排序","hiddenLines":"暗线逻辑","capitalFlow":"资金判断","strategy":"明日策略","risks":["风险1","风险2"]}}"""
    try:
        req = urllib.request.Request('https://api.deepseek.com/v1/chat/completions',
            data=json.dumps({"model":"deepseek-chat","messages":[{"role":"user","content":prompt}],"max_tokens":800}).encode(),
            headers={'Content-Type':'application/json','Authorization':f'Bearer {KEY}'})
        with urllib.request.urlopen(req, timeout=30) as r:
            ai_text = json.loads(r.read())['choices'][0]['message']['content']
        m = re.search(r'\{[\s\S]*\}', ai_text)
        if m:
            ai = json.loads(m.group())
            recap['sentiment']['note'] = ai.get('sentimentNote','')
            recap['cycle']['nature'] = ai.get('cycleNature','')
            recap['visibleLines'] = ai.get('visibleLines','')
            recap['hiddenLines'] = ai.get('hiddenLines','')
            recap['capitalFlow'] = ai.get('capitalFlow','')
            recap['strategy'] = ai.get('strategy','')
            recap['risks'] = ai.get('risks',[''])
            print("✅ AI分析已生成")
    except Exception as e:
        print(f"⚠️ AI调用失败: {e}")

# ===== 6. 写入 =====
data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'data')
os.makedirs(data_dir, exist_ok=True)
path = os.path.join(data_dir, f'{TODAY}.json')
with open(path,'w',encoding='utf-8') as f:
    json.dump(recap, f, ensure_ascii=False, indent=2)
print(f"✅ {path}")
print(f"   指数: {indices['上证']['close']}({indices['上证']['chg']}) | 涨停{limit_up}/跌停{limit_down} | {recap['totalVolume']}")
