#!/usr/bin/env python3
"""每日复盘 — GitHub Actions 自动运行"""
import json, os, sys, re
from datetime import datetime, timezone, timedelta
import urllib.request

TZ = timezone(timedelta(hours=8))
NOW = datetime.now(TZ)
TODAY = NOW.strftime('%Y-%m-%d')
W = ['周一','周二','周三','周四','周五','周六','周日'][NOW.weekday()]
if NOW.weekday() >= 5: print(f"非交易日"); sys.exit(0)

def api(url):
    req = urllib.request.Request(url, headers={'User-Agent':'Mozilla/5.0','Referer':'https://data.eastmoney.com/'})
    with urllib.request.urlopen(req, timeout=12) as r:
        return json.loads(r.read())

# ===== 指数（最稳定）=====
idx = api("https://push2.eastmoney.com/api/qt/ulist.np/get?fltt=2&fields=f2,f3,f6&secids=1.000001,0.399001,0.399006,1.000688,0.899050")
diffs = idx['data']['diff']
nms = ['上证','深成指','创业板','科创50','北证50']
indices = {}
for i, n in enumerate(nms):
    d = diffs[i]
    indices[n] = {'close': d['f2'], 'chg': f"{d['f3']:+.2f}%", 'vol': round(d.get('f6',0)/1e8)}

# 纳指
nas = "N/A"
try:
    u = api("https://push2.eastmoney.com/api/qt/ulist.np/get?fltt=2&fields=f3&secids=100.NDX")
    nas = f"{u['data']['diff'][0]['f3']:+.2f}%"
except: pass

# 两市合计成交额 = 沪+深
total = round((diffs[0].get('f6',0) + diffs[1].get('f6',0))/1e8)

# ===== 组装 =====
recap = {
    "date":TODAY,"weekday":W,"autoGenerated":True,
    "external":{"nasdaq":nas,"note":"手动补充韩国/费半"},
    "indices":indices,
    "totalVolume":f"{total/10000:.2f}万亿",
    "upCount":0,"downCount":0,"limitUp":0,"limitDown":0,
    "poolStatus":[],
    "sentiment":{"note":""},
    "cycle":{"stage":"","nature":"","pivot":"6.15","days":(NOW-datetime(2026,6,15,tzinfo=TZ)).days},
    "selfQA":"","strategy":"","visibleLines":"","hiddenLines":"","capitalFlow":"","risks":[""],
    "ladder":[],"keyMoments":[],"auction":[],"newsEvents":[],"divergence":[],"seeSaw":[],"volumeProfile":[]
}

# ===== AI 分析（用指数数据推断）=====
KEY = os.environ.get('DEEPSEEK_KEY','')
if KEY:
    s = f"上证{indices['上证']['close']}({indices['上证']['chg']}) 深成指{indices['深成指']['chg']} 创业板{indices['创业板']['chg']} 科创50{indices['科创50']['chg']} 北证{indices['北证50']['chg']}。成交{recap['totalVolume']}。纳指{nas}。"
    prompt = f"""A股复盘。{s}根据指数表现和成交额推断今日市场特征。输出JSON:{{"sentimentNote":"情绪定性","cycleNature":"周期阶段","visibleLines":"明线方向","hiddenLines":"暗线逻辑","capitalFlow":"资金判断","strategy":"明日策略","risks":["风险1","风险2"]}}"""
    try:
        req = urllib.request.Request('https://api.deepseek.com/v1/chat/completions',
            data=json.dumps({"model":"deepseek-chat","messages":[{"role":"user","content":prompt}],"max_tokens":800}).encode(),
            headers={'Content-Type':'application/json','Authorization':f'Bearer {KEY}'})
        with urllib.request.urlopen(req, timeout=30) as r:
            t = json.loads(r.read())['choices'][0]['message']['content']
        m = re.search(r'\{[\s\S]*\}', t)
        if m:
            ai = json.loads(m.group())
            for k in ['sentimentNote','cycleNature','visibleLines','hiddenLines','capitalFlow','strategy']:
                if k in ai: recap['sentiment' if k=='sentimentNote' else 'cycle' if k=='cycleNature' else k]['note' if k=='sentimentNote' else 'nature' if k=='cycleNature' else k] = ai[k]
            recap['sentiment']['note']=ai.get('sentimentNote','')
            recap['cycle']['nature']=ai.get('cycleNature','')
            recap['visibleLines']=ai.get('visibleLines','')
            recap['hiddenLines']=ai.get('hiddenLines','')
            recap['capitalFlow']=ai.get('capitalFlow','')
            recap['strategy']=ai.get('strategy','')
            recap['risks']=ai.get('risks',[''])
            print("✅ AI已生成")
    except Exception as e: print(f"⚠️ AI: {e}")

data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'data')
os.makedirs(data_dir,exist_ok=True)
path = os.path.join(data_dir,f'{TODAY}.json')
with open(path,'w',encoding='utf-8') as f: json.dump(recap,f,ensure_ascii=False,indent=2)
print(f"✅ {path} | {nms[0]}{indices['上证']['close']}({indices['上证']['chg']}) | 纳指{nas} | 成交{recap['totalVolume']}")
