#!/usr/bin/env python3
"""每日复盘数据抓取 + AI分析 — 只抓确定能拿到的数据"""
import json, os, sys, re
from datetime import datetime, timezone, timedelta
import urllib.request

TZ = timezone(timedelta(hours=8))
NOW = datetime.now(TZ)
TODAY = NOW.strftime('%Y-%m-%d')
WEEKDAYS = ['周一','周二','周三','周四','周五','周六','周日']
WEEKDAY = WEEKDAYS[NOW.weekday()]
if NOW.weekday() >= 5: print(f"非交易日"); sys.exit(0)

def fetch(url, as_json=True):
    req = urllib.request.Request(url, headers={'User-Agent':'Mozilla/5.0','Referer':'https://data.eastmoney.com/'})
    with urllib.request.urlopen(req, timeout=12) as r:
        return json.loads(r.read()) if as_json else r.read().decode()

# ===== 指数（这个最稳定）=====
idx = fetch("https://push2.eastmoney.com/api/qt/ulist.np/get?fltt=2&fields=f2,f3,f6&secids=1.000001,0.399001,0.399006,1.000688,0.899050")
diffs = idx['data']['diff']
names = ['上证','深成指','创业板','科创50','北证50']
indices = {}
for i, n in enumerate(names):
    d = diffs[i]
    indices[n] = {'close': d['f2'], 'chg': f"{d['f3']:+.2f}%", 'vol': round(d.get('f6',0)/1e8)}

# 涨跌家数 - 用指数页面HTML抓取
up_count = dn_count = 0
try:
    html = fetch("https://quote.eastmoney.com/center/gridlist.html#hs_a_board", as_json=False)
    # 从HTML提取上涨下跌家数
    m1 = re.search(r'"f170":(\d+)', html)
    m2 = re.search(r'"f171":(\d+)', html)
    if m1: up_count = int(m1.group(1))
    if m2: dn_count = int(m2.group(1))
except: pass

# 涨跌停 - 从涨停板页面抓取
limit_up = limit_down = 0
try:
    html = fetch("https://data.eastmoney.com/stockdata/", as_json=False)
    m = re.search(r'涨停.*?(\d+)', html)
    if m: limit_up = int(m.group(1))
except: pass

# 美股
nasdaq_chg = "N/A"
try:
    us = fetch("https://push2.eastmoney.com/api/qt/ulist.np/get?fltt=2&fields=f3&secids=100.NDX")
    nasdaq_chg = f"{us['data']['diff'][0]['f3']:+.2f}%"
except: pass

# 池子（精简到最核心的8只，拆两批）
pool_cfg = [
    ("1.000636","风华高科"),("1.600176","中国巨石"),("1.603986","兆易创新"),
    ("0.000811","冰轮环境"),("1.605111","新洁能"),("0.600183","生益科技"),
    ("0.002384","东山精密"),("0.002281","光迅科技"),
]
pool_status = []
for code, name in pool_cfg:
    try:
        d = fetch(f"https://push2.eastmoney.com/api/qt/stock/get?secid={code}&fields=f2,f3")
        chg = d['data']['f3']
        st = '🟢' if chg>0 else ('🔴' if chg<-5 else ('🟡' if chg<0 else '⚪'))
        pool_status.append({'status':st,'stock':name,'today':f"{chg:+.2f}%",'ma5':'站上' if chg>-3 else '边缘'})
    except: pass

total_vol = sum(d.get('f6',0) for d in diffs)/1e8

# ===== 组装 =====
recap = {
    "date":TODAY,"weekday":WEEKDAY,"autoGenerated":True,
    "external":{"nasdaq":nasdaq_chg,"note":""},
    "indices":indices,
    "totalVolume":f"{total_vol/10000:.2f}万亿",
    "upCount":up_count,"downCount":dn_count,"limitUp":limit_up,"limitDown":limit_down,
    "poolStatus":pool_status,
    "sentiment":{"limitUp":limit_up,"limitDown":limit_down,"upCount":up_count,"downCount":dn_count,"note":""},
    "cycle":{"stage":"","nature":"","pivot":"6.15","days":(NOW-datetime(2026,6,15,tzinfo=TZ)).days},
    "selfQA":"","strategy":"","visibleLines":"","hiddenLines":"","capitalFlow":"","risks":[""],
    "ladder":[],"keyMoments":[],"auction":[],"newsEvents":[],"divergence":[],"seeSaw":[],"volumeProfile":[]
}

# ===== AI =====
KEY = os.environ.get('DEEPSEEK_KEY','')
if KEY and indices.get('上证'):
    best = '，'.join([f"{p['stock']}{p['today']}" for p in pool_status[:5]]) or '无'
    p = f"A股复盘。上证{indices['上证']['close']}({indices['上证']['chg']})深成指{indices['深成指']['chg']}创{indices['创业板']['chg']}科创{indices['科创50']['chg']}。成交{recap['totalVolume']}。涨停约{limit_up}跌停约{limit_down}。涨{up_count}跌{dn_count}。纳指{nasdaq_chg}。池子:{best}。输出JSON:{{\"sentimentNote\":\"情绪\",\"cycleNature\":\"周期\",\"visibleLines\":\"明线\",\"hiddenLines\":\"暗线\",\"capitalFlow\":\"资金\",\"strategy\":\"策略\",\"risks\":[\"风险1\"]}}"
    try:
        req = urllib.request.Request('https://api.deepseek.com/v1/chat/completions',
            data=json.dumps({"model":"deepseek-chat","messages":[{"role":"user","content":p}],"max_tokens":800}).encode(),
            headers={'Content-Type':'application/json','Authorization':f'Bearer {KEY}'})
        with urllib.request.urlopen(req, timeout=30) as r:
            t = json.loads(r.read())['choices'][0]['message']['content']
        m = re.search(r'\{[\s\S]*\}', t)
        if m:
            ai = json.loads(m.group())
            recap['sentiment']['note']=ai.get('sentimentNote','')
            recap['cycle']['nature']=ai.get('cycleNature','')
            recap['visibleLines']=ai.get('visibleLines','')
            recap['hiddenLines']=ai.get('hiddenLines','')
            recap['capitalFlow']=ai.get('capitalFlow','')
            recap['strategy']=ai.get('strategy','')
            recap['risks']=ai.get('risks',[''])
            print("✅ AI已生成")
    except Exception as e: print(f"⚠️ AI: {e}")

data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'data')
os.makedirs(data_dir,exist_ok=True)
path = os.path.join(data_dir,f'{TODAY}.json')
with open(path,'w',encoding='utf-8') as f: json.dump(recap,f,ensure_ascii=False,indent=2)
print(f"✅ {path} | 上证{indices['上证']['close']}({indices['上证']['chg']}) | 涨跌停约{limit_up}/{limit_down}")
